### ISSUE TITLE
 RubySG Online Meetup (June 2020), 2020-06-16

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#10]
# Details

RubySG Online Meetup (June 2020)
16th June 2020

### Link to Online Meetup

To be found on meetup.com

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 1940 | @libsyz, Prima - Scraping with Foot Traffic | 
| 2010 | @taykangsheng JSON Web Tokens? | 
| 2030 | Jobs Shoutout | 
| 2035 | Next meet up advertisement | 
| 2040 | Connect with us! | 
| 2045 | Goodnight! |  

### Sync with other platforms 
- [x] post on [Meetup.com](https://www.meetup.com/Singapore-Ruby-Group/)
- [x] post on [Facebook](https://www.facebook.com/groups/singaporerubybrigade/)
- [x] post on [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg)

**Comment by TayKangSheng** [comment]
I thinking of talking about JWT and `ruby-jwt`

**Comment by libsyz** [comment]
_Speaker_: Miguel Jimenez & Prima Aulia Gusta
_Topic_: Scraping with Foot Traffic
_Talk Outline_: In this presentation, Prima and Miguel will showcase the Foot Traffic Gem, a wrapper for Ferrum designed to run website testing and scrape information off websites. This gem was released by our colleagues at Le Wagon, and we would love to get some feedback from the community. 
_Duration_: 30 min
