### ISSUE TITLE
RubySG Online Meetup (July 2020), 2020-07-16

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#12]
# Details

RubySG Online Meetup (July 2020)
16th July 2020

### Link to Online Meetup

**Zoom**
Meeting ID: 845 8287 9256
Password: 7W@w&pK@YL
https://us02web.zoom.us/j/84582879256?pwd=V3FtazlMeXF0SzdraHNGK3NIMTU0Zz09 

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 1940 | frozen_record by Kang Sheng | 
| 2005 | Jobs Shoutout | 
| 2010 | Next meet up advertisement | 
| 2015 | Connect with us! | 
| 2020 | Goodnight! |  

### Sync with other platforms / people
- [x] post on [Meetup.com](https://www.meetup.com/Singapore-Ruby-Group/)
- [x] post on [Facebook](https://www.facebook.com/groups/singaporerubybrigade/)
- [x] post on [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg)
- [x] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.

**Comment by TayKangSheng** [comment]
I'm changing the meetup to the 3rd Thursday of the week instead because I'm having lessons on Tuesdays.

**Comment by TayKangSheng** [comment]
I'm gonna share about a gem called "frozen_record"
https://rubygems.org/gems/frozen_record

**Comment by miccheng** [comment]
Video of @TayKangSheng's presentation: https://engineers.sg/v/4066
