### ISSUE TITLE
RubySG Online Meetup (August 2020), 2020-08-20

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#14]
# Details

RubySG Online Meetup (August 2020)
20th August 2020

### Link to Online Meetup

Link: https://us02web.zoom.us/j/85890486010?pwd=Qk8rVnpCTFZFT3lGc0NXRjZwZG1mZz09
Meeting ID: 858 9048 6010
Passcode: Ah6*#@UL!8

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 2000 | Speaker 1 | 
| 2020 | Jobs Shoutout | 
| 2025 | Next meet up advertisement | 
| 2030 | Goodnight! |  

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] 1st Thursday reminder - **Call for proposal**.
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [x] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [x] Create Meetup.com event for the next meetup.
    - [x] Create meetup event slides for the upcoming meetup.

**Comment by TayKangSheng** [comment]
I'm thinking of exploring https://github.com/ruby/curses and share it on the meetup.

**Comment by miccheng** [comment]
Video of @TayKangSheng's presentation: https://youtu.be/XWbwD3QB7dM
