### ISSUE TITLE
RubySG Online Meetup (September 2020), 2020-09-17

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#15]
# Details

RubySG Online Meetup (September 2020)
17th September 2020

### Link to Online Meetup

Meeting ID: `84730218706`
Passcode: `H3=@ArHDV?`
https://us02web.zoom.us/j/84730218706?pwd=YXhTUDhRY09XK1B6Q0pVYkIrTWpRQT09

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 2000 | Speaker 1 | 
| 2020 | Jobs Shoutout | 
| 2025 | Next meet up advertisement | 
| 2030 | Goodnight! |  

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] 1st Thursday reminder - **Call for proposal**.
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [x] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [x] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [x] Create Meetup.com event for the next meetup.
    - [x] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by TayKangSheng** [comment]
### Speaker's Name
Kang Sheng

### Title of the Talk
Content Security Policy with Rails

### Description of talk 
Content Security Policy (CSP) is like a browser side firewall that helps protect against attacks such as XSS. By specifying the policy, the browser will follow your specifications to whitelist the assets that are allowed to be loaded on your website. It is really easy to configure CSP in Rails, but you might accidentally break your site when not done properly. In this talk, we will go through what is CSP and how can we roll it out safely to secure your website.

### Contact 
Twitter: @taykangsheng

**Comment by Gregcake** [comment]
### Speaker's Name
Greg Tan

### Title of the Talk
Monitoring with Datadog

### Description of talk
Datadog is a SaaS monitoring and analytics platform that enables visibility into your stack at any scale. Learn how you can use Datadog to keep track your infrastructure, understand application performance, leverage your logs and more.

### Contact
Email: greg.tan@datadoghq.com
