### ISSUE TITLE
RubySG Online Meetup (December 2020), 2020-10-17

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#18]
# Details

RubySG Online Meetup (October 2020)
17th December 2020

### Link to Online Meetup

- [ ] TBC

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 2000 | Speaker 1 | 
| 2020 | Jobs Shoutout | 
| 2025 | Next meet up advertisement | 
| 2030 | Goodnight! |  

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [ ] 1st Thursday reminder - **Call for proposal**.
    - [ ] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [ ] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [ ] Create Meetup.com event for the next meetup.
    - [ ] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by priya-cardup** [comment]
@TayKangSheng Can you please share the meeting link?

**Comment by TayKangSheng** [comment]
Hey @priya-cardup! Sorry I messed up. I'm sorry I didn't had the time to figure this event out and I also forgot to cancel the event!! 😔🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by TayKangSheng** [comment]
If you would still like to join our meetup! The next one will most likely be in Jan! Hope to see you then.

**Comment by priya-cardup** [comment]
> If you would still like to join our meetup! The next one will most likely be in Jan! Hope to see you then.

Sure. Please keep us updated about the next one. Thanks!
