### ISSUE TITLE
How does it work? Meetup #2 suggestions

### ISSUE THREAD

**Issue by arnvald** [rubysg/meetups#2]
Hi!

In this issue you can vote on the library we'll try to learn and understand on the next meetup. In the comments I'll add libraries that you suggested during today's meetup.
I think we can meet the next time around 7th of July, so let's vote until 20th of June - this will give us ~2 weeks to read a bit of code.

Rules: vote by adding reactions to comments in this thread. :-1: means -1 point, all the other reactions ( 🎉 ❤️ 👍  etc) are worth +1 point. Everyone can vote once for each project (multiple reactions won't be counted)

**Comment by arnvald** [comment]
CSRF (not as a project, but as part of Rails): https://github.com/rails/rails

**Comment by arnvald** [comment]
Concurrent-ruby: https://github.com/ruby-concurrency/concurrent-ruby

**Comment by arnvald** [comment]
Bundler: https://github.com/bundler/bundler

**Comment by arnvald** [comment]
Rack: https://github.com/rack/rack

**Comment by arnvald** [comment]
Sidekiq: https://github.com/mperham/sidekiq

**Comment by arnvald** [comment]
Bower-rails: https://github.com/rharriso/bower-rails

**Comment by arnvald** [comment]
Arel: https://github.com/rails/arel

**Comment by juny4ng** [comment]
Devise

**Comment by flyfy1** [comment]
Railtie

> Railtie is the core of the Rails framework and provides several hooks to extend
> Rails and/or modify the initialization process.
> 
> Every major component of Rails (Action Mailer, Action Controller,
> Action View and Active Record) is a Railtie. Each of
> them is responsible for their own initialization. This makes Rails itself
> absent of any component hooks, allowing other components to be used in
> place of any of the Rails defaults.

**Comment by arnvald** [comment]
Ok, voting finished. We've decided to learn how `concurrent-ruby` works! I'll create a meetup soon and post guidelines on how to start. Thanks everyone for submitting proposals and voting!
