### ISSUE TITLE
RubySG Online Meetup (April 2021), 2021-04-15

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#23]
# Details

RubySG Online Meetup (April 2021)
15th April 2021

### Link to Online Meetup

Meeting ID: 856 3807 7200
Passcode: h2&Lc!&yf=
https://us02web.zoom.us/j/85638077200?pwd=akduZy9pdDJVSTl5SzVHNWNCSUpqQT09

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist Meet & Greet~! 🌵 |
| 1945 | What the heck is Zeitwerk @TayKangSheng  |
| 2005 | Breakout rooms |
| 2020 | Jobs Shoutout, Next meetup advertisement |
| 2030 | Goodnight! 🌕 | 

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [ ] 1st Thursday reminder - **Call for proposal**.
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [x] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [x] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [x] Create Meetup.com event for the next meetup.
    - [x] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by TayKangSheng** [comment]
I'm thinking of doing a quick dive into Zeitwerk, the new default autoloader in Rails 6. What the heck is Zeitwerk???

**Comment by miccheng** [comment]
Video of the presentation: https://youtu.be/nRdnqvnmqGc
