### ISSUE TITLE
 RubySG Meetup (July 2021), 2021-07-15

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#26]
I'm planning to have a physical meetup for July if the situation allows. The last physical meetup is in January, and now its good time to have it again.

The last time we did an in person meetup and we met up at a burger place. I open a Google form and I planned to group folks randomly. We only ended up with 1 group because 7 people attended. (Then 8 people were allowed).

This time round, there are some things we need to figure out:
* How many people can be together at once?
* Probably we can’t dine in, then should we ask folks to bring their own food?
* If we eat out then where should we go? 
* if we are in groups but all at the same place, is there risk that we will get fined?

The outcome I’m looking for is just to have folks know each other and build some friendship. Eventually we can build a strong (ruby) software engineering community

# The plan 

- [ ] Get participants to sign up with Google form.
- [ ] Organisers to group people into groups of 5 based on participants preferences.
- [ ] Organisers to help facilitate and each group can decide where they want to meet. Organiser to remind people to be inclusive and make sure to pick somewhere suitable and agreeable by the majority. According to government's announcements, it is likely possible for 5 pax dine. 
- [ ] Organisers to remind and collect a group photo from each group.
- [ ] Collect feedback from all participants.

### Meetup details
**Date:** 15th July 2021
**Time:** 7.30pm to late (recommended)
**Location:** tbd by each group

**Comment by adriangohjw** [comment]
@TayKangSheng should be `2021-07-15` instead! haha

**Comment by TayKangSheng** [comment]
* Looked up [MOH website](https://www.moh.gov.sg/covid-19/faqs). dinning in can only 2 pax and social can gather groups of 5. 
* KIV [Straits Times article](https://www.straitstimes.com/singapore/politics/larger-groups-of-five-diners-expected-to-be-allowed-from-july-12-lawrence-wong) to allow dining in for groups of 5 from july 12.

Plan:
1. Group folks in random groups of 5. Organiser can create a chat group for each group to be closed after the meet up so that we can funnel conversations back to RubySG telegram group. 
2. Each group can decide where they want to meet up. If groups are having trouble to decide, organiser can assist in giving suggestions. 
3. Get each group to take a group photo for https://ruby.sg.
4. Collect feedback using a google form.

**Comment by TayKangSheng** [comment]
![IMG_4642](https://user-images.githubusercontent.com/10722197/126343043-386ad32a-8303-40aa-a639-3605cd79afba.JPG)
![IMG_4640](https://user-images.githubusercontent.com/10722197/126343073-51702e60-71ff-45ea-b35b-66a404815018.JPG)
