### ISSUE TITLE
Ruby Code Reading Group - meetup #3 suggestions

### ISSUE THREAD

**Issue by arnvald** [rubysg/meetups#3]
Hi!

In this issue you can vote on the library we'll try to learn and understand on the next meetup. In the comments I'll add libraries that you suggested during today's meetup.
I think we can meet the next time around 11th of August, so let's vote until 28st of July - this will give us ~2 weeks to read a bit of code.

Rules: 
- suggest a topic by adding a comment
- vote by adding reactions to comments in this thread. 👎 means -1 point, all the other reactions ( 🎉 ❤️ 👍 etc) are worth +1 point.
- Everyone can vote once for each project (multiple reactions won't be counted)

**Comment by arnvald** [comment]
Kleisli - a collection of monads for Ruby

https://github.com/txus/kleisli

**Comment by arnvald** [comment]
Roda - Routing Tree Web Framework Toolkit

https://github.com/jeremyevans/roda

**Comment by Drenmi** [comment]
Maybe we can add some popular ones from the previous votes? 😀

**Comment by arnvald** [comment]
@Drenmi good idea!

Rack: https://github.com/rack/rack (previously 3 votes)

**Comment by arnvald** [comment]
Arel: https://github.com/rails/arel (previously 4 votes)

**Comment by arnvald** [comment]
CSRF (not as a project, but as part of Rails): https://github.com/rails/rails (previously 3 votes)

**Comment by arnvald** [comment]
Sidekiq: https://github.com/mperham/sidekiq (previously 2 votes)

**Comment by Drenmi** [comment]
(I think `rack` is particularly interesting, since Aaron mentioned at Taiwan Ruby Conference last year that he plans to start work on a new, backwards incompatible, version sometime soon.)

**Comment by arnvald** [comment]
Ok, no more votes, we go with `rack` then!

**Comment by Drenmi** [comment]
I recommend everyone watch [this talk](https://www.youtube.com/watch?v=u5AaZRVhecI) by Aaron, from RubyConf Taiwan last year.
