### ISSUE TITLE
RubySG Online Meetup (Sept 2021), 2021-09-16 

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#31]
# Details

**Behind the Gems 2**
16th September 2021
7.30pm - 8.30pm
https://us02web.zoom.us/j/88399980916?pwd=Qm1wTzRCd1l0dUVXWUFBallCUkE3Zz09

### Meetup description
![ruby-2guestspeaker-edwin (1)](https://user-images.githubusercontent.com/10722197/130650790-0f1c0770-3094-4b9e-b54c-07b9e3fc4f6e.jpg)

```text
🌵 For August's meet up, we will be having our second of six series of Behind the Gems, RubySG Miniseries.

We are inviting makers from the Ruby community to share with us their journey and what they have built. We are very honoured to have Edwin, co-founder & CTO of Talenox, to share with us about his experience building the company. Edwin started Talenox as a way for him to build a good team to work together and for them to express their creativity on a shared canvas by helping others. Talenox is the friendliest, automated HR software on the cloud trusted by more than 1000 happy companies.

➡️ Find all details in the GitHub issue below.
https://github.com/rubysg/meetups/issues/31
➡️ Join the RubySG telegram group for more updates! 
https://t.me/joinchat/TWJ3HtLeJF81EweA
```

### Link to Online Meetup

- [ ] TBC 

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist Meet & Greet~! 🌵 |
| 1945 | Edwin - Journey building [Talenox](https://www.talenox.com/) |
| 2005 | Q&A |
| 2015 | Jobs Shoutout, Next meetup advertisement |
| 2030 | Goodnight! 🌕 | 

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] ~1st Thursday reminder - **Call for proposal**.~
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [x] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [ ] Create Meetup.com event for the next meetup.
    - [ ] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by adriangohjw** [comment]
Join us on zoom: `https://us02web.zoom.us/j/88399980916?pwd=Qm1wTzRCd1l0dUVXWUFBallCUkE3Zz09`

**Comment by TayKangSheng** [comment]
https://github.com/rubysg/meetups/issues/28
