### ISSUE TITLE
RubySG Online Meetup (Oct 2021), 2021-10-21

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#32]
# Details

**Behind the Gems 3**
21st October 2021

### Meetup description

🌵 For October's meet up, we will be having our third of six series of Behind the Gems, RubySG Miniseries.

We are inviting makers from the Ruby community to share with us their journey and what they have built. We are very happy to have Hemali, to share with us about her experience building a backend system for an NGO called [Project Smile](https://www.sgprojectsmile.com). While volunteering for Project Smile, Hemali realised that the NGO manages all their workflow with Pen & Paper and Excels; so she decided to build Project Smile App to let them spend more time doing the things that matters.

➡️ Find all details in the GitHub issue below.
https://github.com/rubysg/meetups/issues/32
➡️ Join the RubySG telegram group for more updates! 
https://t.me/joinchat/TWJ3HtLeJF81EweA

### Link to Online Meetup

https://www.meetup.com/Singapore-Ruby-Group/events/281117091

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist Meet & Greet~! 🌵 |
| 1945 | Hermali - Journey building a backend system for an NGO called [Project Smile](https://www.sgprojectsmile.com) |
| 2005 | Q&A |
| 2015 | Jobs Shoutout, Next meetup advertisement |
| 2030 | Goodnight! 🌕 | 

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] ~1st Thursday reminder - **Call for proposal**.~
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [ ] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [ ] Create Meetup.com event for the next meetup.
    - [ ] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by adriangohjw** [comment]
Engineers SG Virtual Meetup is inviting you to a scheduled Zoom meeting.

Topic: RubySG Behind The Gems :: 3 / 6
Time: Oct 21, 2021 07:30 PM Singapore

Join Zoom Meeting
https://us02web.zoom.us/j/87873332229?pwd=YWExVEZPa0taSlBiV2lKZ0l3THNqZz09

Meeting ID: 878 7333 2229
Passcode: @eyB6r@E0%
One tap mobile
+6531651065,,87873332229#,,,,*4653277319# Singapore
+6531587288,,87873332229#,,,,*4653277319# Singapore

Dial by your location
        +65 3165 1065 Singapore
        +65 3158 7288 Singapore
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
Meeting ID: 878 7333 2229
Passcode: 4653277319
Find your local number: https://us02web.zoom.us/u/kb5GKG7MVW

**Comment by TayKangSheng** [comment]
https://github.com/rubysg/meetups/issues/28
