### ISSUE TITLE
RubySG Online Meetup (Nov 2021), 2021-11-18

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#33]
# Details

**Behind the Gems 4**
18th November 2021

### Meetup description

🌵 For November's meet up, we will be having our fourth of six series of Behind the Gems, RubySG Miniseries.

We are inviting makers from the Ruby community to share with us their journey and what they have built. For this month, I will be sharing some of my learnings when building YetAnotherYear. YetAnotherYear is a New Year's Resolutions app that literally lets you keep track of your new year's resolutions. In this talk, I will be focusing on my learnings trying to build a fully functional SPA on Rails. Rails cookie auth for your SPA? Serve assets with Rails to be used in SPA? Managing OAuth using Rails for SPA? Yes, Rails can still do most of the heavy lifting so that I can just manage 1 Heroku instance 🤷‍♂️

➡️ Find all details in the GitHub issue below.
https://github.com/rubysg/meetups/issues/33
➡️ Join the RubySG telegram group for more updates! 
https://t.me/joinchat/TWJ3HtLeJF81EweA

### Link to Online Meetup

https://www.meetup.com/Singapore-Ruby-Group/events/281970965/
https://us02web.zoom.us/j/86128990473?pwd=aEZjdmxhL085blFrMXYzWlA5am1KZz09

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist Meet & Greet~! 🌵 |
| 1945 | Kang Sheng - YetAnotherYear |
| 2005 | Q&A |
| 2015 | Jobs Shoutout, Next meetup advertisement |
| 2030 | Goodnight! 🌕 | 

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] ~1st Thursday reminder - **Call for proposal**.~
    - [ ] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [ ] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [ ] Create Meetup.com event for the next meetup.
    - [ ] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by adriangohjw** [comment]
Engineers SG Virtual Meetup is inviting you to a scheduled Zoom meeting.

Topic: Behind The Gems :: 4 / 6
Time: Nov 18, 2021 07:30 PM Singapore

Join Zoom Meeting
https://us02web.zoom.us/j/86128990473?pwd=aEZjdmxhL085blFrMXYzWlA5am1KZz09

Meeting ID: 861 2899 0473
Passcode: 9S?KKAp0.D
One tap mobile
+6531651065,,86128990473#,,,,*8461433569# Singapore
+6531587288,,86128990473#,,,,*8461433569# Singapore

Dial by your location
        +65 3165 1065 Singapore
        +65 3158 7288 Singapore
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
Meeting ID: 861 2899 0473
Passcode: 8461433569
Find your local number: https://us02web.zoom.us/u/kC06eyzbR

**Comment by TayKangSheng** [comment]
https://github.com/rubysg/meetups/issues/28
