### ISSUE TITLE
RubySG Online Meetup (Feb 2022), 2022-02-17

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#35]
# Details

**Behind the Gems 5**
17th February 2022

### Meetup description

🌵Heeeello y’all 👋 It’s February 2022 and its another month for another RubySG meet up! We will be having our next series of Behind the Gems, RubySG Miniseries.

We are inviting makers from the Ruby community to share with us their journey and what they have built. For this month, We are ecstatic to have Jerald Gan from Airfoil to share with us about his journey building Mira, a platform for reading and sharing newsletters! Jerald started this project to learn more about Ruby on Rails and was surprised to find out about the amount of information email newsletter hold! Find out more about Mira at https://www.onmira.app/ 🤩

➡️ Find all details in the GitHub issue below.
https://github.com/rubysg/meetups/issues/35
➡️ Join the RubySG telegram group for more updates! 
https://t.me/joinchat/TWJ3HtLeJF81EweA

### Link to Online Meetup

https://www.meetup.com/Singapore-Ruby-Group/events/283883566/

### Zoom Link

https://us02web.zoom.us/j/86796722973?pwd=cEJwMTUyT0FOam5vdmU2UDFEWlNRdz09

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist Meet & Greet~! 🌵 |
| 1945 | Jerald Gan - Mira |
| 2005 | Q&A |
| 2015 | Jobs Shoutout, Next meetup advertisement |
| 2030 | Goodnight! 🌕 | 

## Organizer's Action Items

1. Reminders. All reminders should go on to [Facebook](https://www.facebook.com/groups/singaporerubybrigade/) and [Telegram](https://t.me/joinchat/BPfX501idx5NSmdANkOrtg). 
    - [x] ~1st Thursday reminder - **Call for proposal**.~
    - [x] 2nd Thursday reminder - **Announce plans and lineup**.
    - [ ] 3rd Thursday reminder - **Remind to come online**.
1. Recordings
    - [ ] Get recording arranged. Ask Engineers.SG whether they can support the event, if not arrange for recording somehow.
1. Before meetup event preparation
    - [ ] Create Meetup.com event for the next meetup.
    - [ ] Create meetup event slides for the upcoming meetup.

## Speaker's Action Items

1. Comment in this issue with the following information:
    - Speaker's Name
    - Title of the talk
    - Description of talk (< 70 words)
    - Contact (eg. Email, Twitter Handle)

**Comment by adriangohjw** [comment]
Engineers SG Virtual Meetup is inviting you to a scheduled Zoom meeting.

Topic: RubySG Online Meetup (Feb 2022)
Time: Feb 17, 2022 07:30 PM Singapore

Join Zoom Meeting
https://us02web.zoom.us/j/86796722973?pwd=cEJwMTUyT0FOam5vdmU2UDFEWlNRdz09

Meeting ID: 867 9672 2973
Passcode: 6tYu6H=r=#
One tap mobile
+6531651065,,86796722973#,,,,*0422502889# Singapore
+6531587288,,86796722973#,,,,*0422502889# Singapore

Dial by your location
        +65 3165 1065 Singapore
        +65 3158 7288 Singapore
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
Meeting ID: 867 9672 2973
Passcode: 0422502889
Find your local number: https://us02web.zoom.us/u/kctS0oHmZ2

**Comment by TayKangSheng** [comment]
https://github.com/rubysg/meetups/issues/28
