### ISSUE TITLE
RubySG Meetup (feb 2020), 2020-02-18

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#6]
# 18th February 2020

### Venue arrangements

Google Hangout session link.
https://meet.google.com/xxk-gyav-hhj

### Slides
https://docs.google.com/presentation/d/13TB9zAYBKpvxVmj08ZXqffRzCT5AHM-lLYfEqM0oR9Q/edit?usp=sharing

### Schedule 
- [ ] TODO: A list of events by timing

| time | activity | 
| :--- | :--- |
| 1830 | Door Open, Food and Social |
| 1900 | Shout out for sponsors and schedule for the day |  
| 1905 | Guest Speaker, [replace-with-speaker-handle], [replace-with-topic] |
| 1915 | Break |
| 1920 | @orangethunder Adopting Sorbet |
| 1935 | break |
| 1940 | @TayKangSheng TDD together! Code-along implementing a Simple Stack with TDD |
| 1955 | Jobs shout out! |
| 2005 | Next Meetup advertisement |
| 2010 | Food and Social |
| 2020 | Clean up the venue |
| 2030 | End |

### Sync with other platforms 
- [x] post on [Meetup.com](https://www.meetup.com/Singapore-Ruby-Group/)
- [x] post on [Facebook](https://www.facebook.com/groups/singaporerubybrigade/)
- [x] post on [Slack](rubysg.slack.com)

**Comment by orangethunder** [comment]
I can give a talk on Sorbet.

**Comment by TayKangSheng** [comment]
Hey @orangethunder! I’m thinking of moving the meetup online to Google Hangouts due to the outbreak of Coronavirus. Are you okay with that? You can do a Screenshare when it’s your turn during the session.

I think it’s safer if we don’t congregate for the time being until the epidemic is over. It’s best for everyone.

**Comment by jdickey** [comment]
@TayKangSheng Having tried to do technical presentations over Hangouts, I think the sensible limit for that is about five participants if Q&A sessions are allowed. If people are that spooked of nCoV, we may just as well postpone entirely until things are Officially Back to Normalish. (Yes, the experience _was_ that negative for all concerned; IIRC, the one time we had about 25 participants, there was a 1.8/5 evaluation score, compared to a 4.2/5 score three weeks later from the same presenters to a non-online audience.) [IANAE](https://en.wikipedia.org/wiki/Epidemiology), of course, so I defer to leadership.

**Comment by orangethunder** [comment]
As someone who manages remote teams, I find it frustrating when a meeting exceeds a certain number of participants. I'd rather wait to present when it's possible to do so in person.

**Comment by TayKangSheng** [comment]
Thanks for the input @jdickey @orangethunder. I personally thought that online might work out fine, but I guess experiences speaks for itself. I would also hate it if we have a far from ideal meetup because it might push people away instead of attracting people. 

I will cancel the meetup and re-start it when the situation blows over / its safer to hold a ftf meetup.
