### ISSUE TITLE
RubySG Online Meetup (mar 2020), 2020-03-17

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#7]
# Details

RubySG Online Meetup (March)
17th March 2020

### Link to Online Meetup

https://zoom.us/j/257128836

### Schedule 

| time | activity | 
| :--- | :--- |
| 1900 | Briefing on Webinar format, and DOs and DON'Ts. |
| 1910 | @miccheng, **So you need to deploy Rails on-premise** <br> So you somehow have to deploy a Rails app in your on-premise data center (or on VMs). What are the things to look out for and how do you make it less painful? Michael will be sharing some war stories, gotchas and #TILs that he stumbled upon while deploying Rails on-premise. |
| 1930 | Break |
| 1935 | @TayKangSheng, **Binary Heap and Implementing with TDD** |
| 1955 | Jobs shout out! | 
| 2005 | Next Meetup advertisement |  
| 2010 | End |

### Sync with other platforms 
- [x] post on [Meetup.com](https://www.meetup.com/Singapore-Ruby-Group/)
- [x] post on [Facebook](https://www.facebook.com/groups/singaporerubybrigade/)
- [x] post on [Slack](rubysg.slack.com)

**Comment by TayKangSheng** [comment]
I have decided to try running the meetup webinar style. Lets see how it goes!

**Comment by CoolDrinELiu** [comment]
@TayKangSheng Hi, I'd like to know about the online meetup link of it.

**Comment by TayKangSheng** [comment]
@CoolDrinELiu I will update here and meetup.com with the link soon!

**Comment by CoolDrinELiu** [comment]
@TayKangSheng Thank you~!!

**Comment by CoolDrinELiu** [comment]
@TayKangSheng Hi~! Is the location decided yet? Tomorrow is the day...

**Comment by vinsgit** [comment]
Hi, may i ask when will  the link be updated ?

**Comment by TayKangSheng** [comment]
Hey @vinsgit and @CoolDrinELiu, I have added the link to the description of this issue! Look forward to seeing you guys there! ❤️

**Comment by CoolDrinELiu** [comment]
Yeah! Cheers~!

**Comment by TayKangSheng** [comment]
## Slides for today's meetup!
[RubySG-03-2020.pdf](https://github.com/rubysg/meetups/files/4343404/RubySG-03-2020.pdf)

## Slides for my talk today!
[rubysg-2020_03_17-binary_heap_with_tdd.pdf](https://github.com/rubysg/meetups/files/4343405/rubysg-2020_03_17-binary_heap_with_tdd.pdf)

**Comment by clarencechanxy** [comment]
Thanks @TayKangSheng for the clear sharing! Hi, am the one who talked at the Jobs Shoutout section. Am from Bandwagon (www.bandwagon.asia), our vision is to spread music that inspires and to champion music in Asia. We're a media portal built on rails and currently have an active traffic of 200k / month, 28% from SG, 72% overseas, so there's a humble active base to work with. 

Some of the features we are looking at building: 

- content recommendation system for improved discovery and serving content users would like based on what they listen to or currently consume
- reactions to content (allow ppl to interact more around music they love), music is a passion point, so we should have more ways to interact than just 'like / comment'  
- customising content display based on country and language 
- helping solo concert goers to connect with others 

We currently have 3 developers and they are part time. So we are open to various work arrangements. If the intersection of music and tech is of interest, let me know! 

Will leave you with this video where we hit the streets to find out "What do Singaporeans think about music in SG": https://www.facebook.com/watch/?v=1457958961027018  

Our hope for the future is to make Singapore a music nation. Just like what you may think of LA, London, Berlin, Tokyo, Seoul. It's a long shot but we're taking some active steps, and hopefully, with some of your help, and the combination from other skillsets coming together too, we can get there sooner. 

Thanks in advance,
Clarence

**Comment by miccheng** [comment]
Here’s the notes from my talk: https://docs.google.com/document/d/1VnRdApPP791oXhZTj3JhdLiVpnvRR77kln9cccEFCe8

**Comment by miccheng** [comment]
Video of @TayKangSheng's presentation: https://engineers.sg/v/4016

**Comment by miccheng** [comment]
Video of my presentation: https://engineers.sg/v/4017

**Comment by vinsgit** [comment]
Hey~ @TayKangSheng Im the Chinese rubyist who attended the meet up on March 17, Thank you for sharing with miccheng. If the meet up will be hold online again next time , then I will definitely participate. and Im wondering  if I can join the rubysg.slack

**Comment by TayKangSheng** [comment]
@vinsgit Nice to meet you! 

Can i have your email? I think I definitely have to work out with the admin of the group to have something more automatic :p

**Comment by CoolDrinELiu** [comment]
@TayKangSheng Hi, could you invite me in as well? drineliu@gmail.com, Thanks~!

**Comment by vinsgit** [comment]
@TayKangSheng Ah~ Sorry for the late reply, my email is qs2811531898@gmail.com, thank you very much ~

**Comment by TayKangSheng** [comment]
Hey @vinsgit, the admins feedbacked to me that there was some issues inviting you to the slack group. They have provided me with a self invite link which i have sent you via email. 

look out for an email from `kangsheng@gmail.com` and the subject is `RubySG Slack Group Invite Link`

**Comment by vinsgit** [comment]
@TayKangSheng  I've joined the slack group , Thank you so much

**Comment by TayKangSheng** [comment]
Closing this issue :)
