### ISSUE TITLE
RubySG Online Meetup (apr 2020), 2020-04-21

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#8]
# Details

RubySG Online Meetup (April 2020)
21st April 2020

### Link to Online Meetup

- [ ] TBC

### Schedule 

| time | activity | 
| :--- | :--- |
| 1930 | Rubyist meet and greet~! 👋 |
| 1940 | @vinsgit, Dockerizing Rails | 
| 2005 | @TayKangSheng, Fiber | 
| 2030 | Jobs Shoutout | 
| 2040 | Next Meetup advertisement | 
| 2045 | RubySG Shoutout | 
| 2050 | End of meetup |  

### Sync with other platforms 
- [x] post on [Meetup.com](https://www.meetup.com/Singapore-Ruby-Group/)
- [x] post on [Facebook](https://www.facebook.com/groups/singaporerubybrigade/)
- [x] post on [Slack](rubysg.slack.com)

**Comment by vinsgit** [comment]
Dockerizing rails ,  20 min  , vita

**Comment by TayKangSheng** [comment]
[Uploading RubySG-04-2020.pdf…]()

**Comment by TayKangSheng** [comment]
# Meetup Slides

[RubySG-04-2020.pdf](https://github.com/rubysg/meetups/files/4509921/RubySG-04-2020.pdf)

# Slides from my share
[RubySG-2020_04_21-fiber.pdf](https://github.com/rubysg/meetups/files/4509924/RubySG-2020_04_21-fiber.pdf)

**Comment by miccheng** [comment]
Video of last night's presentations:

- Vita's talk on Dockerizing Rails: <https://engineers.sg/v/4027>
- Kang Sheng's talk on Fiber: <https://engineers.sg/v/4026>

**Comment by TayKangSheng** [comment]
Closing this issue ❤️ Thanks to all that attended the meetup!
